/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: stm32logo                                             *
* Dimensions:  113 * 113                                             *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmstm32logo;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsstm32logo[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palstm32logo = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acstm32logo[] = {
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, __XXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________,
  ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________,
  ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________,
  ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX___X, XXXXX___, ________, ________, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ___XXXXX, ________, ________, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ___XX_XX, XXX_____, ________, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXX___, XXX_____, _XXXXX__, ________, ________, ________,
  ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ____XXXX, X_______, ____XXXX, XX______, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ___XXX__, XXX_____, __XXX___, _XXXX___, ________, ________,
  ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXX_____, _XXX____, ___XXX__, _XX_____, _____X_X, X_______, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, _____X_X, ________, ______XX, X_______, _______X, X_______, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ____XXXX, X_______, _____XX_, ___X____, ______X_, X_______, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XX____, _XXX____, ___XX___, _____XXX, X___XX__, X_______, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XX_____X, XX______, ___XXXX_, _XXX____, _______X, XXXXX___, X_______, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, __XXXXXX, ________, ______XX, XX______, ________, XXX_____, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXX_, ________, ____XXXX, XXXX____, ______XX, XXX____X, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XX_X, XX______, __XXX__X, X___XXX_, ______XX, __X____X, ________, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XX__, _XX_____, XX____XX, XXX___XX, X____X__, _XX____X, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _____X__, ___XX_X_, ___XXXXX, XXXX____, _XXXX___, _X_____X, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _____X__, _____XXX, XXXXXXXX, XXXXXX__, __XX____, _______X, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _____X__, _____XXX, XXXXXXXX, XXXXXXXX, X_X_____, ______XX, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _____X__, _____XX_, XXXXXXXX, XXXXXXXX, X_X_____, _X___XXX, ________, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _____X__, _____XXX, _XXXXXXX, XXXXXXX_, _XX_____, _X__XXX_, ________, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X____X__, _____XXX, X_XXXXXX, XXXX___X, XXX_____, _X_XX_X_, ________, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _XX__X__, _____XXX, XXX_XXXX, XX__XXXX, XXX_____, _XX___X_, ________, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, __XX_X__, _____XXX, XXXX_XXX, __XXXXXX, XX______, _X____X_, ________, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XX_, _____XXX, XXXXX___, XXXXXXXX, XXX___XX, XX____X_, ________, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, _____XXX, XXXXXX_X, XXXXXXXX, XXX___X_, X____X__, ________, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ______X_, XX___XXX, XXXXXX_X, XXXXXXXX, XXX_XX__, X____X__, ________, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ______X_, __XX_XXX, XXXXXX_X, XXXXXXXX, XXXXX___, X____XX_, ________, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ______X_, ___XXXXX, XXXXXX_X, XXXXXXXX, XXX_____, X___XXX_, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____X_, _____XXX, XXXXXX_X, XXXXXXXX, XX______, X__XXXX_, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX____X_, ______XX, XXXXXX_X, XXXXXXXX, XX______, X___XXX_, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____X_, ______XX, XXXXXX_X, XXXXXXXX, XX______, X___XXXX, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X__XX_X_, ______XX, XXXXXX_X, XXXXXXXX, _X_____X, X___XXXX, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X___XXXX, ______XX, _XXXXX_X, XXXXXX__, ______XX, ____XXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, ______XX, ___XXX_X, XXXX____, _____XXX, ____XXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_____X, XX_____X, ___XXX_X, XX______, _X__XX_X, ____XXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_____X, _XXX___X, _____X_X, XX______, _X_X__XX, ___XXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_____X, ___XX__X, ________, _X______, _XX___X_, __XXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX____X, _____XXX, ________, _X______, ______X_, _XXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX___X, ______XX, ________, _X_____X, XX____XX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, _______X, XX______, _X____XX, X_____XX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, __XX____, _X___XX_, X_____XX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, ___XX___, _X__XX__, X____XXX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_____X, ____XXX_, _X______, X___XXXX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX____X, ______XX, XX______, X__XXXXX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, ________, XX______, XXXXXXXX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, ________, X_______, XXXXXXXX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, X______X, XXXXXXXX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, X_____XX, XXXXXXXX, XXXXXXXX, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, X____XXX, XXXXXXXX, XXXXXXXX, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, X___XXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, X__XXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXX_, X_XXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, _XXXXXXX, XXXXXX__, __XX____, _______X, X___XX__, __XXX___, _XXX_XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, __XXXXXX, XXXXX___, ___X____, _______X, X___XX_X, X__XX__X, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, __XXXXXX, XXXXX__X, X__XXX__, XXX____X, X___XX_X, XX_X__XX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ___XXXXX, XXXXX__X, XXXXXX__, XXX____X, ____XXXX, X__XXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ___XXXXX, XXXXX___, __XXXX__, XXX____X, _____XXX, ___XXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ____XXXX, XXXXXX__, ___XXX__, XXX_____, ____XXXX, ___XXXX_, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ____XXXX, XXXXXXXX, ____XX__, XXX_____, ____XXXX, XX_XXX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, _____XXX, XXXX___X, X___XX__, XXX__X__, _X__XXXX, XX_XX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, _____XXX, XXXX____, ____XX__, XXX__X__, _X___X_X, XX_XX_XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________,
  ________, ______XX, XXXXX___, ___XXX__, XXX__X__, _X___X__, ___X____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________,
  ________, _______X, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, _XXXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXX___X_, __XXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXX___X_, _____XX_, _X_____X, XX____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  ________, ________, ___XXXXX, XXXXXXXX, XXX__XXX, XX___XX_, _X______, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  ________, ________, _____XXX, XXXXXXXX, XXX__XXX, XXX__XX_, _X__X___, ___X___X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXX__XXX, XX___XX_, _X__XX__, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXX___XX, _____XX_, _X__XX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________,
  ________, ________, ________, XXXXXXXX, XXX___X_, _____X__, _X__XX__, ___X___X, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________,
  ________, ________, ________, _XXXXXXX, XXX_____, __X_____, _X______, _______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXXX____, _XX_____, _X_____X, XX____XX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________,
  ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________,
  ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmstm32logo = {
  113, // xSize
  113, // ySize
  15, // BytesPerLine
  1, // BitsPerPixel
  _acstm32logo,  // Pointer to picture data (indices)
  &_Palstm32logo   // Pointer to palette
};

/*************************** End of file ****************************/
